"""create_table_recent_songs

Revision ID: 325d1a5c617d
Revises: d02c5e920b58
Create Date: 2026-05-03 19:27:49.089360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325d1a5c617d'
down_revision: Union[str, Sequence[str], None] = 'd02c5e920b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recently_played_songs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.TEXT(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('songs', 'song_id',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_favorite_songs_song_id'), table_name='favorite_songs')
    op.create_index(op.f('ix_favorite_songs_song_id'), 'favorite_songs', [sa.literal_column('song_id NULLS FIRST')], unique=False, postgresql_ops={'song_id': None}, postgresql_using='prefix')
    op.alter_column('favorite_songs', 'song_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('recently_played_songs')
    # ### end Alembic commands ###
