"""add_new_columns_to_users_table

Revision ID: a57506f728d4
Revises: ce90c79ebf9a
Create Date: 2026-04-29 17:00:29.528519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a57506f728d4"
down_revision: Union[str, Sequence[str], None] = "ce90c79ebf9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "favorite_songs",
        "song_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_favorite_songs_song_id"),
        table_name="favorite_songs",
        postgresql_ops={"song_id": None},
        postgresql_using="prefix",
    )
    op.create_index(
        op.f("ix_favorite_songs_song_id"), "favorite_songs", ["song_id"], unique=False
    )
    op.alter_column(
        "songs",
        "song_id",
        existing_type=sa.VARCHAR(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS user_avatar VARCHAR(250)")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS device_token VARCHAR(250)")
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.execute("DROP INDEX IF EXISTS ix_users_email CASCADE")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # downgrade()
    op.execute("DROP INDEX IF EXISTS ix_users_email CASCADE")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("users", "device_token")
    op.drop_column("users", "user_avatar")
    op.alter_column(
        "songs",
        "song_id",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_favorite_songs_song_id"), table_name="favorite_songs")
    op.create_index(
        op.f("ix_favorite_songs_song_id"),
        "favorite_songs",
        [sa.literal_column("song_id NULLS FIRST")],
        unique=False,
        postgresql_ops={"song_id": None},
        postgresql_using="prefix",
    )
    op.alter_column(
        "favorite_songs",
        "song_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
