"""add_missing_user_fields

Revision ID: c9cb8f4b082e
Revises: 8b0b0df3bbf8
Create Date: 2026-04-23 23:58:58.912127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cb8f4b082e'
down_revision: Union[str, Sequence[str], None] = '8b0b0df3bbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
