"""Alter_device_tokens_table

Revision ID: d02c5e920b58
Revises: e9adad3a3e33
Create Date: 2026-04-30 13:28:17.191832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d02c5e920b58"
down_revision: Union[str, Sequence[str], None] = "e9adad3a3e33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("device_tokens_user_id_fkey"), "device_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "device_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("ix_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "songs",
        "song_id",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_favorite_songs_song_id"), table_name="favorite_songs")
    op.create_index(
        op.f("ix_favorite_songs_song_id"),
        "favorite_songs",
        [sa.literal_column("song_id NULLS FIRST")],
        unique=False,
        postgresql_ops={"song_id": None},
        postgresql_using="prefix",
    )
    op.alter_column(
        "favorite_songs",
        "song_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "device_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("device_tokens_user_id_fkey"),
        "device_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
