"""create_device_token_table_and_delete_device_token_colum

Revision ID: e9adad3a3e33
Revises: a57506f728d4
Create Date: 2026-04-29 17:21:28.868844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e9adad3a3e33"
down_revision: Union[str, Sequence[str], None] = "a57506f728d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=250), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("platform", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.drop_column("users", "device_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "device_token", sa.VARCHAR(length=250), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("ix_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "songs",
        "song_id",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_favorite_songs_song_id"), table_name="favorite_songs")
    op.create_index(
        op.f("ix_favorite_songs_song_id"),
        "favorite_songs",
        [sa.literal_column("song_id NULLS FIRST")],
        unique=False,
        postgresql_ops={"song_id": None},
        postgresql_using="prefix",
    )
    op.alter_column(
        "favorite_songs",
        "song_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_table("device_tokens")
    # ### end Alembic commands ###
